apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.deployment.name }}
  # This labels are attached to deployment, wont affect pod behaviour
  labels:
    project: roboshop
    purpose: rs-demo
    tier: frontend
    component: frontend
  annotations:
    kubernetes.io/change-cause: {{ .Values.deployment.changeCause }}
spec:
  replicas: {{ .Values.deployment.replicas }}
  selector:
  # using these labels replica set selects the pod
    matchLabels:
      project: roboshop
      purpose: rs-demo
      tier: frontend
      component: frontend
  template:
   # This is pod definition, pod is subset of replicaset
    metadata:
      labels:
        project: roboshop
        purpose: rs-demo
        tier: frontend
        component: frontend
    spec:
      containers:
      - name: nginx
        image: nginx:{{.Values.deployment.imageVersion}}